hyperskill_project:
  id: 314
  ide_files: https://hyperskill.org/api/projects/314/additional-files/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Thu, 01 Jan 1970 00:00:00 UTC"
stages:
  - id: 1764
    step: 24615
    is_completed: true
  - id: 1765
    step: 24616
    is_completed: true
  - id: 1766
    step: 24617
    is_completed: false
  - id: 1767
    step: 24618
    is_completed: false
  - id: 1768
    step: 24619
    is_completed: false
topics:
  0:
    - title: "Write, compile, and run"
      theory_id: 3739
    - title: Operating systems
      theory_id: 9704
    - title: Command line overview
      theory_id: 8977
    - title: Parameters and options
      theory_id: 9746
    - title: IDE
      theory_id: 10996
    - title: Introduction to Java
      theory_id: 38627
    - title: "Basic literals: numbers, strings and characters"
      theory_id: 3522
    - title: Writing first program
      theory_id: 3521
    - title: Printing data
      theory_id: 3749
    - title: Types and variables
      theory_id: 3518
    - title: Comments
      theory_id: 3520
    - title: Reading user's input with Scanner
      theory_id: 9055
    - title: Coding style conventions
      theory_id: 12411
    - title: Naming variables
      theory_id: 3513
    - title: Arithmetic operations
      theory_id: 3519
    - title: Integer types and operations
      theory_id: 3565
    - title: Increment and decrement
      theory_id: 5008
    - title: Floating-point types and operations
      theory_id: 3517
    - title: Boolean type and operations. True and false
      theory_id: 3516
    - title: Comparing values. Relational operators
      theory_id: 3512
    - title: Conditional statement
      theory_id: 3503
    - title: One-line condition with ternary operator
      theory_id: 3506
    - title: For loop
      theory_id: 3505
    - title: While and do-while loops
      theory_id: 3498
    - title: Break and continue. Branching
      theory_id: 3507
    - title: Declaring methods
      theory_id: 10982
    - title: Primitive data types and their sizes
      theory_id: 3532
    - title: Type casting
      theory_id: 3510
    - title: Calling methods
      theory_id: 10973
    - title: Primitive and reference types
      theory_id: 5035
    - title: Array
      theory_id: 3511
    - title: Characters
      theory_id: 3514
    - title: String
      theory_id: 3523
    - title: Errors in programs
      theory_id: 3536
    - title: First glance at exceptions
      theory_id: 3497
    - title: NullPointerException
      theory_id: 1945
    - title: What are bugs
      theory_id: 5504
    - title: Formatted output
      theory_id: 7046
    - title: Processing strings
      theory_id: 3551
    - title: Array exceptions
      theory_id: 1940
    - title: Debugging overview
      theory_id: 14368
    - title: IntelliJ IDEA
      theory_id: 37202
    - title: Run and debug with IntelliJ IDEA
      theory_id: 37206
    - title: Debugging simple constructs
      theory_id: 16479
    - title: IntelliJ IDEA run configurations
      theory_id: 10630
  1:
    - title: Method "main"
      theory_id: 3489
    - title: "Multiple conditions: switch"
      theory_id: 3504
    - title: Functional decomposition
      theory_id: 10570
    - title: What is object-oriented programming
      theory_id: 3614
    - title: Random class
      theory_id: 4910
    - title: Defining classes
      theory_id: 3618
    - title: Objects and their properties
      theory_id: 4727
  3:
    - title: "Basic terms: JVM, JRE, JDK"
      theory_id: 3499
    - title: Compile and run Java from CLI
      theory_id: 3746
    - title: Overloading
      theory_id: 3525
    - title: Arrays as parameters
      theory_id: 3594
    - title: Constants. Final variables
      theory_id: 7427
    - title: Hierarchy of exceptions
      theory_id: 3570
    - title: Exception handling
      theory_id: 3552
    - title: File class
      theory_id: 3635
    - title: Reading files
      theory_id: 3636
    - title: Writing files
      theory_id: 3652
    - title: Debugging methods
      theory_id: 52095
    - title: Instance methods
      theory_id: 3495
    - title: Grouping classes with packages
      theory_id: 3621
    - title: Initializing new instances. Constructor
      theory_id: 3535
    - title: Access modifiers
      theory_id: 3589
    - title: Getters and setters
      theory_id: 3599
    - title: Inheritance
      theory_id: 3583
    - title: Multiple constructors
      theory_id: 3538
    - title: Keyword "super"
      theory_id: 3588
    - title: Static members
      theory_id: 3534
